
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  projectsSidebar: [{ type: 'autogenerated', dirName: 'projects' }], // ✅ Matches config
  contactsSidebar: [{ type: 'autogenerated', dirName: 'contacts' }], // ✅ Fixed typo from 'contactSidebar'
};
//helllo world

export default sidebars;

